"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type Classification = "PROTOCOL" | "SIMULATOR_INTERNAL" | "SIMULATOR_SCENARIO" | "UNSPECIFIED";
type Scenario = "NORMAL" | "VERIFY_UNRESOLVED" | "KNOWN_REVERSED";
type Profile = "NORMAL" | "PRE_EXECUTION_HTTP_FAILURE" | "POST_EXECUTION_HTTP_FAILURE" | "POST_EXECUTION_MALFORMED_SOAP" | "POST_EXECUTION_DELAY";
type Operation = "bpVerifyRequest" | "bpSettleRequest" | "bpVerifySettleRequest";
type Callback = { attempted: boolean; status: "NOT_ATTEMPTED" | "SUCCEEDED" | "FAILED"; attemptedAt?: string; completedAt?: string; failureCategory?: string; httpStatus?: number; classification: "SIMULATOR_INTERNAL" };
type PendingFault = { profile: Exclude<Profile, "NORMAL">; operation: Operation; consumption: "ONE_SHOT"; classification: "SIMULATOR_SCENARIO" };
type Transaction = {
  transactionId: string; refId?: string; paymentOperation: "PAY" | "DYNAMIC_PAY" | "CUMULATIVE_DYNAMIC_PAY"; terminalId: string; orderId: string; saleOrderId?: string; saleReferenceId?: string; amount: string;
  saleState: string; verificationState: string; settlementState: string; reversalState: string; lifecycleState: string;
  callback: Callback; scenario: Scenario; pendingTransportFault?: PendingFault; createdAt: string; updatedAt: string;
};
type Event = { eventId: string; at: string; type: string; classification: Classification; metadata: Record<string, string | number> };
type Detail = Transaction & { saleResCode?: string; saleCompletedAt?: string; verificationAttemptedAt?: string; verifiedAt?: string; settlementRequestedAt?: string; reversedAt?: string; events: Event[] };
type Summary = { transactionCount: number; successfulSales: number; verified: number; settlementRequested: number; knownReversed: number; semanticScenarios: number; pendingTransportFaults: number };
type ListResponse = { classification: "SIMULATOR_INTERNAL"; summary: Summary; transactions: Transaction[] };

const scenarios: readonly Scenario[] = ["NORMAL", "VERIFY_UNRESOLVED", "KNOWN_REVERSED"];
const profiles: readonly Profile[] = ["NORMAL", "PRE_EXECUTION_HTTP_FAILURE", "POST_EXECUTION_HTTP_FAILURE", "POST_EXECUTION_MALFORMED_SOAP", "POST_EXECUTION_DELAY"];
const operations: readonly Operation[] = ["bpVerifyRequest", "bpSettleRequest", "bpVerifySettleRequest"];

export function DashboardHome() {
  const [data, setData] = useState<ListResponse>();
  const [error, setError] = useState<string>();
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [saleFilter, setSaleFilter] = useState("ALL");
  const [verificationFilter, setVerificationFilter] = useState("ALL");
  const [scenarioFilter, setScenarioFilter] = useState("ALL");

  const refresh = useCallback(async () => {
    setLoading(true); setError(undefined);
    try {
      const response = await fetch("/local/api/transactions?limit=100", { cache: "no-store" });
      if (!response.ok) throw new Error("Could not load local simulator diagnostics.");
      setData(await response.json() as ListResponse);
    } catch { setError("Could not load local simulator diagnostics. Check local server, then refresh."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void refresh(); }, 0); return () => window.clearTimeout(timer); }, [refresh]);

  const transactions = useMemo(() => (data?.transactions ?? []).filter((transaction) => {
    const needle = search.trim().toLowerCase();
    const matchesSearch = needle.length === 0 || [transaction.refId, transaction.orderId, transaction.saleOrderId, transaction.saleReferenceId].some((value) => value?.toLowerCase().includes(needle));
    return matchesSearch && (saleFilter === "ALL" || transaction.saleState === saleFilter) && (verificationFilter === "ALL" || transaction.verificationState === verificationFilter) && (scenarioFilter === "ALL" || transaction.scenario === scenarioFilter);
  }), [data, saleFilter, scenarioFilter, search, verificationFilter]);

  return <main className="dashboard-shell">
    <DashboardHeader onRefresh={() => void refresh()} loading={loading} />
    <section className="dashboard-notice" aria-label="Local simulator notice"><strong>Unofficial local developer tool.</strong> In-memory diagnostics only. No real payment, banking action, or merchant administration occurs here.</section>
    <section aria-labelledby="status-heading" className="space-y-3"><div className="section-heading"><div><p className="eyebrow">SIMULATOR_INTERNAL</p><h2 id="status-heading">Simulator status</h2></div><StateBadge value="PROCESS_LOCAL / IN_MEMORY" tone="neutral" /></div>
      <div className="metric-grid">{metricCards(data?.summary).map(([label, value]) => <article className="metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>local diagnostic</small></article>)}</div>
    </section>
    <section className="dashboard-grid" aria-label="Simulator capabilities"><InfoCard title="Supported local protocol operations" classification="PROTOCOL"><ul className="compact-list"><li>bpPayRequest</li><li>bpDynamicPayRequest (safe normal path)</li><li>bpCumulativeDynamicPayRequest (safe normal path)</li><li>bpVerifyRequest</li><li>bpSettleRequest</li><li>bpVerifySettleRequest</li><li>bpInquiryRequest</li><li>bpReversalRequest</li></ul></InfoCard><InfoCard title="Semantic scenarios" classification="SIMULATOR_SCENARIO"><p>NORMAL, VERIFY_UNRESOLVED, and KNOWN_REVERSED. Bounded, transaction-scoped local controls.</p></InfoCard><InfoCard title="One-shot transport faults" classification="SIMULATOR_SCENARIO"><p>Pre/post execution faults for Verify, Settle, and VerifySettle. They are merchant-observation tests, not protocol state.</p></InfoCard></section>
    <section aria-labelledby="transactions-heading" className="panel"><div className="section-heading"><div><p className="eyebrow">SIMULATOR_INTERNAL</p><h2 id="transactions-heading">Transactions</h2><p>Recent process-local transactions. Refresh after external merchant SOAP activity.</p></div></div>
      <div className="filter-bar"><label>Search identifiers<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="RefId, orderId, Sale ID" /></label><Filter label="Sale" value={saleFilter} values={["ALL", "PENDING", "SUCCEEDED", "NON_SUCCESS"]} onChange={setSaleFilter} /><Filter label="Verify" value={verificationFilter} values={["ALL", "NOT_ATTEMPTED", "ATTEMPTED", "VERIFIED"]} onChange={setVerificationFilter} /><Filter label="Scenario" value={scenarioFilter} values={["ALL", ...scenarios]} onChange={setScenarioFilter} /></div>
      {error ? <ErrorMessage message={error} /> : loading && data === undefined ? <p className="empty-state">Loading local diagnostics…</p> : transactions.length === 0 ? <p className="empty-state">No local transactions match. Send a fake local Pay request, then refresh.</p> : <TransactionTable transactions={transactions} />}
    </section>
    <ClassificationLegend />
  </main>;
}

export function TransactionDetail({ transactionId }: { transactionId: string }) {
  const [data, setData] = useState<Detail>();
  const [error, setError] = useState<string>();
  const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => {
    setLoading(true); setError(undefined);
    try { const response = await fetch(`/local/api/transactions/${encodeURIComponent(transactionId)}`, { cache: "no-store" }); if (response.status === 404) throw new Error("This local transaction no longer exists."); if (!response.ok) throw new Error("Could not load transaction diagnostics."); setData(await response.json() as Detail); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load transaction diagnostics."); } finally { setLoading(false); }
  }, [transactionId]);
  useEffect(() => { const timer = window.setTimeout(() => { void refresh(); }, 0); return () => window.clearTimeout(timer); }, [refresh]);
  if (error) return <main className="dashboard-shell"><DashboardHeader onRefresh={() => void refresh()} loading={loading} /><ErrorMessage message={error} /><Link className="back-link" href="/local">Back to dashboard</Link></main>;
  if (data === undefined) return <main className="dashboard-shell"><DashboardHeader onRefresh={() => void refresh()} loading={loading} /><p className="empty-state">Loading transaction diagnostics…</p></main>;
  return <main className="dashboard-shell"><DashboardHeader onRefresh={() => void refresh()} loading={loading} /><Link className="back-link" href="/local">← All transactions</Link><section className="detail-title"><div><p className="eyebrow">LOCAL TRANSACTION / SIMULATOR_INTERNAL</p><h1>Transaction lifecycle</h1><code>{data.refId ?? "RefId not assigned"}</code></div><StateBadge value={data.lifecycleState} tone={toneFor(data.lifecycleState)} /></section>
    <section className="dashboard-notice"><strong>Observation and narrow local controls only.</strong> Opening this page does not execute SOAP, send callbacks, append events, consume scenarios, or consume transport faults.</section>
    <section className="detail-grid"><InfoCard title="Overview" classification="SIMULATOR_INTERNAL"><DefinitionList rows={[["Amount", data.amount], ["Sale", data.saleState], ["Verification", data.verificationState], ["Settlement", data.settlementState], ["Reversal", data.reversalState], ["Created", formatTime(data.createdAt)], ["Latest activity", formatTime(data.updatedAt)]]} /></InfoCard><InfoCard title="Protocol identifiers" classification="PROTOCOL"><DefinitionList mono rows={[["Request operation", data.paymentOperation], ["terminalId", data.terminalId], ["Payment orderId", data.orderId], ["SaleOrderId", data.saleOrderId ?? "—"], ["SaleReferenceId", data.saleReferenceId ?? "—"], ["RefId (case-sensitive)", data.refId ?? "—"]]} /></InfoCard></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">SIMULATOR_INTERNAL lifecycle display</p><h2>Lifecycle</h2></div></div><Lifecycle transaction={data} /></section>
    <section className="detail-grid"><InfoCard title="Callback diagnostics" classification="SIMULATOR_INTERNAL"><CallbackPanel callback={data.callback} /></InfoCard><ScenarioControl transaction={data} onChanged={refresh} /><TransportControl transaction={data} onChanged={refresh} /></section>
    <section className="panel" aria-labelledby="events-heading"><div className="section-heading"><div><p className="eyebrow">SAFE APPEND-ONLY VIEW</p><h2 id="events-heading">Event history</h2></div></div><EventHistory events={data.events} /></section>
    <ClassificationLegend />
  </main>;
}

function DashboardHeader({ onRefresh, loading }: { onRefresh: () => void; loading: boolean }) { return <header className="dashboard-header"><div><p className="eyebrow">UNOFFICIAL / LOCAL / DEVELOPER TOOL</p><h1>Behpardakht Simulator</h1><p>Safe transaction diagnostics and deterministic test controls.</p></div><button className="button secondary" type="button" onClick={onRefresh} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</button></header>; }
function metricCards(summary?: Summary): [string, number][] { return [["Transactions", summary?.transactionCount ?? 0], ["Successful Sales", summary?.successfulSales ?? 0], ["Verified", summary?.verified ?? 0], ["Settlement requested", summary?.settlementRequested ?? 0], ["Known reversed", summary?.knownReversed ?? 0], ["Semantic scenarios", summary?.semanticScenarios ?? 0], ["Pending transport faults", summary?.pendingTransportFaults ?? 0]]; }
function Filter({ label, value, values, onChange }: { label: string; value: string; values: readonly string[]; onChange: (value: string) => void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function InfoCard({ title, classification, children }: { title: string; classification: Classification; children: React.ReactNode }) { return <article className="info-card"><div className="card-title"><h2>{title}</h2><ClassificationBadge classification={classification} /></div>{children}</article>; }
function StateBadge({ value, tone }: { value: string; tone: "good" | "warn" | "bad" | "neutral" }) { return <span className={`state-badge ${tone}`}>{humanize(value)}</span>; }
function ClassificationBadge({ classification }: { classification: Classification }) { return <span className="classification-badge">{classification}</span>; }
function TransactionTable({ transactions }: { transactions: readonly Transaction[] }) { return <div className="table-wrap"><table><thead><tr><th>RefId</th><th>Operation / orderId</th><th>Sale IDs</th><th>Amount</th><th>States</th><th>Callback</th><th>Scenario / fault</th><th>Latest activity</th></tr></thead><tbody>{transactions.map((transaction) => <tr key={transaction.transactionId}><td><Link href={`/local/transactions/${encodeURIComponent(transaction.transactionId)}`} className="identifier">{transaction.refId ?? "—"}</Link></td><td className="identifier">{transaction.paymentOperation}<br />{transaction.orderId}</td><td className="identifier">{transaction.saleOrderId ?? "—"}<br />{transaction.saleReferenceId ?? ""}</td><td className="identifier">{transaction.amount}</td><td><StateBadge value={transaction.saleState} tone={toneFor(transaction.saleState)} /><StateBadge value={transaction.verificationState} tone={toneFor(transaction.verificationState)} /><StateBadge value={transaction.settlementState} tone={toneFor(transaction.settlementState)} /><StateBadge value={transaction.reversalState} tone={toneFor(transaction.reversalState)} /></td><td><StateBadge value={transaction.callback.status} tone={toneFor(transaction.callback.status)} /></td><td><StateBadge value={transaction.scenario} tone={toneFor(transaction.scenario)} />{transaction.pendingTransportFault && <span className="small-code">{transaction.pendingTransportFault.profile}<br />{transaction.pendingTransportFault.operation}</span>}</td><td>{formatTime(transaction.updatedAt)}</td></tr>)}</tbody></table></div>; }
function DefinitionList({ rows, mono = false }: { rows: readonly (readonly [string, string])[]; mono?: boolean }) { return <dl className="definition-list">{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd className={mono ? "identifier" : undefined}>{value}</dd></div>)}</dl>; }
function Lifecycle({ transaction }: { transaction: Detail }) { const stages = [["Pay created", true], ["Sale", transaction.saleState !== "PENDING"], ["Verify", transaction.verificationState !== "NOT_ATTEMPTED"], ["Settlement request", transaction.settlementState === "REQUESTED"]] as const; return <div><ol className="lifecycle">{stages.map(([label, complete]) => <li key={label} className={complete ? "complete" : "pending"}><span>{complete ? "●" : "○"}</span><div><strong>{label}</strong><small>{lifecycleText(label, transaction)}</small></div></li>)}</ol>{transaction.reversalState === "REVERSED" && <p className="reversed-note"><StateBadge value="KNOWN REVERSED" tone="bad" /> Simulator knows reversed state. This does not claim bpReversalRequest completed.</p>}</div>; }
function lifecycleText(stage: string, transaction: Detail) { if (stage === "Sale") return transaction.saleState; if (stage === "Verify") return transaction.verificationState; if (stage === "Settlement request") return transaction.settlementState === "REQUESTED" ? "REQUESTED" : "Not requested"; return formatTime(transaction.createdAt); }
function CallbackPanel({ callback }: { callback: Callback }) { return <><p><StateBadge value={callback.status} tone={toneFor(callback.status)} /></p><DefinitionList rows={[["Attempted", callback.attempted ? "Yes" : "No"], ["Attempt", callback.attemptedAt ? formatTime(callback.attemptedAt) : "—"], ["Completed", callback.completedAt ? formatTime(callback.completedAt) : "—"], ["Failure category", callback.failureCategory ?? "—"], ["HTTP status", callback.httpStatus?.toString() ?? "—"]]} /><p className="subtle">Destination URL and callback body are intentionally not shown.</p></>; }
function ScenarioControl({ transaction, onChanged }: { transaction: Detail; onChanged: () => Promise<void> }) { const [scenario, setScenario] = useState<Scenario>(transaction.scenario); const [message, setMessage] = useState<string>(); const [saving, setSaving] = useState(false); async function submit() { if (!transaction.refId) return setMessage("Scenario control needs an assigned RefId."); setSaving(true); setMessage(undefined); const response = await fetch("/local/api/scenarios", scenario === "NORMAL" ? { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ refId: transaction.refId }) } : { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ refId: transaction.refId, scenario }) }); if (!response.ok) { setMessage(await safeError(response, "Scenario action rejected.")); } else { setMessage("Scenario control updated."); await onChanged(); } setSaving(false); } return <InfoCard title="Semantic scenario" classification="SIMULATOR_SCENARIO"><p className="subtle">Current: <strong>{transaction.scenario}</strong></p><label className="control-label">Scenario<select value={scenario} onChange={(event) => setScenario(event.target.value as Scenario)}>{scenarios.map((item) => <option key={item}>{item}</option>)}</select></label><button className="button" type="button" onClick={() => void submit()} disabled={saving}>{saving ? "Saving…" : scenario === "NORMAL" ? "Clear scenario" : "Assign scenario"}</button><p className="subtle">VERIFY_UNRESOLVED forces deterministic unresolved Verify without inventing provider ResCode. KNOWN_REVERSED forces eligible local known state; it is not bpReversalRequest.</p>{message && <ControlMessage message={message} />}</InfoCard>; }
function TransportControl({ transaction, onChanged }: { transaction: Detail; onChanged: () => Promise<void> }) { const [profile, setProfile] = useState<Profile>(transaction.pendingTransportFault?.profile ?? "NORMAL"); const [operation, setOperation] = useState<Operation>(transaction.pendingTransportFault?.operation ?? "bpVerifyRequest"); const [message, setMessage] = useState<string>(); const [saving, setSaving] = useState(false); async function submit() { if (!transaction.refId) return setMessage("Transport control needs an assigned RefId."); setSaving(true); setMessage(undefined); const response = await fetch("/local/api/transport-faults", profile === "NORMAL" ? { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ refId: transaction.refId }) } : { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ refId: transaction.refId, profile, operation }) }); if (!response.ok) setMessage(await safeError(response, "Transport action rejected.")); else { setMessage("One-shot transport control updated."); await onChanged(); } setSaving(false); } return <InfoCard title="Pending transport fault" classification="SIMULATOR_SCENARIO"><p className="subtle">{transaction.pendingTransportFault ? `${transaction.pendingTransportFault.profile} / ${transaction.pendingTransportFault.operation}` : "None pending"}</p><label className="control-label">Profile<select value={profile} onChange={(event) => setProfile(event.target.value as Profile)}>{profiles.map((item) => <option key={item}>{item}</option>)}</select></label><label className="control-label">Target operation<select value={operation} onChange={(event) => setOperation(event.target.value as Operation)}>{operations.map((item) => <option key={item}>{item}</option>)}</select></label><button className="button" type="button" onClick={() => void submit()} disabled={saving}>{saving ? "Saving…" : profile === "NORMAL" ? "Clear fault" : "Assign one-shot fault"}</button><p className="subtle">PRE fails before operation, no state change. POST profiles commit operation first, then change merchant observation. Fixed and local only.</p>{message && <ControlMessage message={message} />}</InfoCard>; }
function EventHistory({ events }: { events: readonly Event[] }) { return <ol className="event-list">{events.map((event) => <li key={event.eventId}><div><strong>{event.type}</strong><span>{formatTime(event.at)}</span></div><ClassificationBadge classification={event.classification} /><dl>{Object.entries(event.metadata).map(([key, value]) => <div key={key}><dt>{key}</dt><dd className="identifier">{value}</dd></div>)}</dl></li>)}</ol>; }
function ClassificationLegend() { return <section className="legend"><h2>Classification</h2><p><ClassificationBadge classification="PROTOCOL" /> Behavior grounded in supplied v1.39.</p><p><ClassificationBadge classification="SIMULATOR_INTERNAL" /> Local implementation or diagnostic detail; never a provider claim.</p><p><ClassificationBadge classification="SIMULATOR_SCENARIO" /> Developer-controlled deterministic local test behavior.</p><p><ClassificationBadge classification="UNSPECIFIED" /> v1.39 does not establish enough provider behavior for claim.</p></section>; }
function ErrorMessage({ message }: { message: string }) { return <p className="error-message" role="alert">{message}</p>; }
function ControlMessage({ message }: { message: string }) { return <p className="control-message" role="status">{message}</p>; }
async function safeError(response: Response, fallback: string) { try { const body = await response.json() as { error?: unknown }; return typeof body.error === "string" ? body.error : fallback; } catch { return fallback; } }
function formatTime(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "—" : date.toLocaleString(); }
function humanize(value: string) { return value.replaceAll("_", " "); }
function toneFor(value: string): "good" | "warn" | "bad" | "neutral" { if (["SUCCEEDED", "VERIFIED", "REQUESTED", "NORMAL", "NOT_ATTEMPTED", "NOT_REVERSED", "NOT_ATTEMPTED"].includes(value)) return value === "NORMAL" || value.startsWith("NOT_") ? "neutral" : "good"; if (["FAILED", "NON_SUCCESS", "REVERSED", "KNOWN_REVERSED"].includes(value)) return "bad"; if (["ATTEMPTED", "VERIFY_UNRESOLVED", "PENDING", "AWAITING_SALE", "VERIFY_PENDING"].includes(value)) return "warn"; return "neutral"; }
